version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocritic
    - gocyclo
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - zerologlint

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: context-keys-type
          disabled: true
    gosec:
      excludes:
        - G114  # http.ListenAndServe timeout - acceptable for this project
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - bodyclose
          - errorlint
          - testifylint
          - staticcheck
          - gosmopolitan
          - musttag
