# Cloud Build configuration for CI/CD
# Triggered on push to main branch
# See ADR: docs/adr/20251218-cicd.md

steps:
  # Build and push with ko
  # See ADR: docs/adr/20251224-cloud-build-image.md
  - name: 'cgr.dev/chainguard/ko'
    env:
      - KO_DOCKER_REPO=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/web
    args:
      - 'build'
      - '.'
      - '--bare'
      - '-t'
      - '$SHORT_SHA'

  # Update Cloud Run image (service managed by Terraform)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/web:$SHORT_SHA'
      - '--region=${_REGION}'

options:
  logging: CLOUD_LOGGING_ONLY
