# Cloud Build configuration for CI/CD
# Triggered on push to main branch
# See ADR: docs/adr/20251218-cicd.md

steps:
  # Build and push with ko
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    env:
      - 'KO_DOCKER_REPO=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        GO_VERSION=$$(grep "^go " go.mod | awk '{print $$2}')
        curl -sSfL https://go.dev/dl/go$${GO_VERSION}.linux-amd64.tar.gz | tar -C /usr/local -xzf -
        export PATH=/usr/local/go/bin:$$PATH
        go install github.com/google/ko@latest
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev --quiet
        $$(go env GOPATH)/bin/ko build . --bare -t $SHORT_SHA

  # Update Cloud Run image (service managed by Terraform)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}:$SHORT_SHA'
      - '--region=${_REGION}'

options:
  logging: CLOUD_LOGGING_ONLY
