# Cloud Build configuration for CI/CD
# Triggered on push to main branch
# See ADR: docs/adr/20251218-cicd.md

steps:
  # Configure Docker for Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker ${_REGION}-docker.pkg.dev --quiet
        cp -r ~/.docker /workspace/.docker

  # Build and push with ko
  - name: 'golang:1'
    entrypoint: 'bash'
    env:
      - 'DOCKER_CONFIG=/workspace/.docker'
    args:
      - '-c'
      - |
        go install github.com/google/ko@latest
        export KO_DOCKER_REPO=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}
        /go/bin/ko build . --bare -t $SHORT_SHA -t latest

  # Update Cloud Run image (service managed by Terraform)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}:$SHORT_SHA'
      - '--region=${_REGION}'

options:
  logging: CLOUD_LOGGING_ONLY
